# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Build minimal, immutable OCI images from enterprise Linux base distributions"
  homepage "https://github.com/damnhandy/distill"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.0/distill_darwin_amd64.tar.gz"
      sha256 "8d3976e1b401b76490137890f777f69d38126981eb3264ce64da3da312585d55"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.0/distill_darwin_arm64.tar.gz"
      sha256 "7ab91a349383912285c1e679ef9d9209f4328884f36ca5fcd252e4fc4f6cda7f"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.0/distill_linux_amd64.tar.gz"
      sha256 "605409765cfafe3dae239eefec6e08e51d0f3fa2294376a921f3d113940f3360"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.0/distill_linux_arm64.tar.gz"
      sha256 "0af2698fbda614efbf751a7d7aca790a5d7742d9abc85f6da4ccb02367fd5d9a"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  test do
    system "#{bin}/distill", "version"
  end
end
