# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Build minimal, immutable OCI images from enterprise Linux base distributions"
  homepage "https://github.com/damnhandy/distill"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.1/distill_darwin_amd64.tar.gz"
      sha256 "b9188bf03bde26c69bc14d550093f4529d938e6261938301635b6bb09e9f4632"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.1/distill_darwin_arm64.tar.gz"
      sha256 "20cc66628f2f7d7c409c9637472317f220bebefee7f302e73455ddd1fc0f2f97"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.1/distill_linux_amd64.tar.gz"
      sha256 "c9accf093b870d4ff4424d02c9f8430e4632691928f00d33bb8e4b6c5c2bc9f9"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/damnhandy/distill/releases/download/v0.3.1/distill_linux_arm64.tar.gz"
      sha256 "f4227ab3dcba876843dafa24425abf942af615447f744108f7e787b9b6489f90"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  test do
    system "#{bin}/distill", "version"
  end
end
